#!/bin/sh

xcodebuild -workspace Edge.xcworkspace -scheme Edge -configuration Test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES build-for-testing test-without-building | xcpretty
slather coverage
